### ISSUE TITLE
Add google analytics to know interactions

### ISSUE THREAD

**Issue by safaldas-neoito** [manjubhaskar02/Resume#2]
https://analytics.google.com/

**Comment by manjubhaskar02** [comment]
Hi @safaldas-neoito , I have updated google analytics . https://github.com/manjubhaskar02/Resume/commit/aba8f77c7c7914546b472d713ccaf0fa777a36f4

**Comment by manjubhaskar02** [comment]
Thank you

**Comment by safaldas-neoito** [comment]
Nice
